nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: ['http://localhost:3000']
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['OPTIONS', 'GET', 'POST', 'PUT', 'DELETE']
    max_age: 3600
  paths:
    '^/api/':
      allow_origin: ['http://localhost:3000']
      allow_headers: ['Content-Type', 'Authorization']
      allow_methods: ['OPTIONS', 'GET', 'POST', 'PUT', 'DELETE']
      max_age: 3600
